version: "3"

volumes:
  postgres_data:
    driver: local
  wildfly_data:
    driver: local

services:
  wildfly:
    build:
      context: ./quickstarts-wildfly/
    volumes:
      - wildfly_data:/data
    ports:
      - "8888:8080"
      - "9990:9990"
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:8.0.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_LOGLEVEL: DEBUG
      JAVA_OPTS: "-Djboss.socket.binding.port-offset=100 -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
    ports:
      - 8180:8180
      - 8000:8000
    volumes:
      - ./custom-theme/:/opt/jboss/keycloak/themes/custom-theme
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 8088:80
  techlab-jsclient:
    image: nginx:latest
    ports:
      - 8082:8082
    volumes:
      - ./js-console/web-resources/:/usr/share/nginx/html:Z
      - ./js-console/default-nginx.conf:/etc/nginx/conf.d/default.conf:ro,Z
  techlab-service:
    build:
      dockerfile: Dockerfile
      context: ./nodejs-backend
    network_mode: host
    ports:
      - 3001:3001
  gatekeeper:
    image: quay.io/keycloak/keycloak-gatekeeper:8.0.1
    depends_on:
      - "keycloak"
      - "httpbin"
    ports:
      - 3000:3000
    environment:
      - PROXY_LISTEN=0.0.0.0:3000
      - PROXY_DISCOVERY_URL=http://keycloak:8180/auth/realms/techlab
      - PROXY_CLIENT_ID=lab-gatekeeper
      - PROXY_CLIENT_SECRET=72549906-9b1d-43fc-9988-11360c9ebd57
    command:
      - --verbose=true
      - --redirection-url=http://localhost:3000
      - --secure-cookie=false
      - --encryption-key=AgXa7xRcoClDEU0ZDSH4X0XhL5Qy2Z2j
      - --enable-refresh-tokens=true
      - --enable-session-cookies=true
      - --enable-default-deny=true
      - --enable-logging=true
      - --resources=uri=/*
      - --upstream-url=http://httpbin:80
  openldap:
    image: rroemhild/test-openldap
    ports:
      - 389:389
