version: "3"

volumes:
  postgres_data:
    driver: local
  wildfly_data:
    driver: local

services:
  wildfly:
    build:
      context: ./quickstarts-wildfly/
    volumes:
      - wildfly_data:/data
    ports:
      - "8888:8080"
      - "9990:9990"
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_LOGLEVEL: DEBUG
      JAVA_OPTS: "-Djboss.socket.binding.port-offset=100 -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
    ports:
      - 8180:8180
      - 8000:8000
    volumes:
      - ./custom-theme/:/opt/jboss/keycloak/themes/custom-theme
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 8088:80
  techlab-jsclient:
    image: nginx:latest
    ports:
      - 8082:8082
    volumes:
      - ./js-console/web-resources/:/usr/share/nginx/html:Z
      - ./js-console/default-nginx.conf:/etc/nginx/conf.d/default.conf:ro,Z
  techlab-service:
    build:
      dockerfile: Dockerfile
      context: ./nodejs-backend
    network_mode: host
    ports:
      - 3001:3001
  oauth2proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
    ports:
      - 3000:3000
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:3000
      OAUTH2_PROXY_UPSTREAMS: http://httpbin:80
      OAUTH2_PROXY_REDIRECT_URL: http://localhost:3000
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_CLIENT_ID: lab-proxy
      OAUTH2_PROXY_CLIENT_SECRET: 86bc47ba-9ecb-41b0-9947-8ba4291fab83
      OAUTH2_PROXY_OIDC_ISSUER_URL: http://keycloak:8180/auth/realms/techlab
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_COOKIE_SECRET: somerandomstring12341234567890AB
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_SCOPE: "openid profile email"
      #OAUTH2_PROXY_COOKIE_REFRESH: "5m"
      OAUTH2_PROXY_USER_ID_CLAIM: "preferred_username"
      #OAUTH2_PROXY_SSL_UPSTREAM_INSECURE_SKIP_VERIFY: "true"
  proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
    ports:
      - 3333:3333
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:3333
      OAUTH2_PROXY_UPSTREAMS: http://httpbin:80
      OAUTH2_PROXY_REDIRECT_URL: http://localhost:3333
      OAUTH2_PROXY_PROVIDER: keycloak
      OAUTH2_PROXY_CLIENT_ID: lab-proxy
      OAUTH2_PROXY_CLIENT_SECRET: 86bc47ba-9ecb-41b0-9947-8ba4291fab83
      OAUTH2_PROXY_LOGIN_URL: http://keycloak:8180/auth/realms/techlab/protocol/openid-connect/auth
      OAUTH2_PROXY_REDEEM_URL: http://keycloak:8180/auth/realms/techlab/protocol/openid-connect/token
      OAUTH2_PROXY_VALIDATE_URL: http://keycloak:8180/auth/realms/techlab/protocol/openid-connect/userinfo
      #OAUTH2_PROXY_OIDC_JWKS_URL: http://keycloak:8180/auth/realms/techlab/protocol/openid-connect/certs
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_COOKIE_SECRET: somerandomstring12341234567890AB
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      #OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_SCOPE: "openid profile email"
      OAUTH2_PROXY_USER_ID_CLAIM: "email"
      ##OAUTH2_PROXY_SSL_UPSTREAM_INSECURE_SKIP_VERIFY: "true"
      OAUTH2_PROXY_KEYCLOAK_GROUP: "/user"
  openldap:
    image: rroemhild/test-openldap
    ports:
      - 389:389

